### ISSUE TITLE
Remove "Put Downs" from ReadMe

### ISSUE THREAD

**Issue by adamtoakley** [jgoakley/hassio-addons#2]
The ReadMe has lots of "I don't know what I'm doing" or "I super suck at life" you should consider removing these statements as they do not align with the Community Guidelines

😁

**Comment by jgoakley** [comment]
> The ReadMe has lots of "I don't know what I'm doing" or "I super suck at life" you should consider removing these statements as they do not align with the Community Guidelines
> 
> 😁

Request denied @adamtoakley 😋
