### ISSUE TITLE
Addon Fails to start

### ISSUE THREAD

**Issue by meichthys** [jgoakley/hassio-addons#3]
I receive the following when trying to start the addon using driver: `weewx.drivers.vantage`
![image](https://user-images.githubusercontent.com/10717998/169453079-88dfe76e-88d8-4724-a337-4036c975eb59.png)

**Comment by jgoakley** [comment]
@meichthys I am able to replicate the error you were receiving on my setup as well.  I updated the addon to use the latest version of WeeWX (among other updates). As part of those updates I'm getting a python logging error (which seems to only affect logging).

My Accurite weather station is working with the current version and when I change it the weewx.drivers.vantage driver WeeWX appears to be looking for a /dev/ttyUSB0 device that I do not have. It may be a USB to serial adapter that is part of the Vantage device. Either way it may we worth checking to see if your weather station works with this updated version.

**Comment by meichthys** [comment]
@jgoakley Thanks for following up, but I've since moved to running weewx in a VM, so I probably won't get around to testing this.
